# -*- coding: utf-8 -*-
"""Convert the transparent-background portrait PNG into ASCII grids.

Glyph density follows brightness, so the lit face carries the detail and
the hair/suit recede. Inverting this for the light theme was tried and
abandoned: the subject is almost entirely dark, so an inverted ramp has no
tonal variation to work with and collapses into a flat slab. Both themes
therefore share one grid and differ only in ink colour.

Everything below FLOOR collapses to a single faint glyph
rather than being dithered down the ramp - a dithered shadow reads as
scattered noise, a quantised one reads as a solid mass and carries the
silhouette.
"""
import os
from PIL import Image

SRC = r"C:\Users\devlynxz\Downloads\FORMAL_PICTURE-removebg-preview.png"
COLS, ROWS = 56, 26
RAMP = ".`:;~+=*coO#8@"
DARK = ":"   # sits mid-cell; a backtick clings to the top and reads as dashes
FLOOR = 0.30
GAMMA = 0.85

img = Image.open(SRC).convert("RGBA")

# crop to the subject via the alpha channel
alpha = img.getchannel("A")
img = img.crop(alpha.point(lambda p: 255 if p > 24 else 0).getbbox())
print("source", img.size)

L = list(img.convert("L").resize((COLS, ROWS), Image.LANCZOS).getdata())
A = list(img.getchannel("A").resize((COLS, ROWS), Image.LANCZOS).getdata())

inside = sorted(L[i] for i in range(len(L)) if A[i] > 110)
lo = inside[int(len(inside) * 0.02)]
hi = inside[int(len(inside) * 0.98)]
print("lum range", lo, hi)


def grid():
    rows = []
    for r in range(ROWS):
        line = []
        for c in range(COLS):
            i = r * COLS + c
            if A[i] <= 110:
                line.append(" ")
                continue
            t = (L[i] - lo) / float(max(1, hi - lo))
            t = min(1.0, max(0.0, t))
            if t < FLOOR:
                line.append(DARK)
                continue
            t = ((t - FLOOR) / (1.0 - FLOOR)) ** GAMMA
            line.append(RAMP[int(round(t * (len(RAMP) - 1)))])
        rows.append("".join(line))
    return rows


rows = grid()
for r in rows:
    print("|" + r + "|")

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "portrait.py")
with open(out, "w", encoding="utf-8") as fh:
    fh.write("# -*- coding: utf-8 -*-\n")
    fh.write("# generated by photo_to_ascii.py from "
             "FORMAL_PICTURE-removebg-preview.png\n")
    fh.write("COLS, ROWS = %d, %d\n" % (COLS, ROWS))
    fh.write("DARK = %r\n" % DARK)
    fh.write("\nPORTRAIT = [\n")
    for r in rows:
        fh.write("    %r,\n" % r)
    fh.write("]\n")
print("\nwrote", out)
